#' Standard ggplot2 theme for plots generated by lcmsMetab
#'
#' A simple coding time saver for developer plot aesthetic preferences.
#'
#' @import ggplot2
#'
#' @return returns a ggplot2 theme object
#' @export

ggThemeLcmsMetab <- function() {

  theme.std <-
    ggplot2::theme(title = element_text(size = 10),
          axis.title = element_text(size = 9),
          axis.text.x = element_text(size = 8),
          axis.text.y = element_text(size = 8),
          panel.background = element_blank(),
          panel.border = element_rect(fill = NA, linetype = 1, size = .5),
          panel.grid.major.y = element_line(colour = "grey50", size = 0.1),
          panel.grid.major.x = element_blank())

  return(theme.std)


}
